#!/bin/bash

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ -d "/home/$USER/.bashrc" ]]; then
    echo "Couldn't find a bashrc file at /home/$USER"
    exit 1
fi

if [[ ! -d "/home/$USER/.aliaser" ]]; then
    mkdir -p /home/$USER/.aliaser/bin
fi

if [[ ! -f "/home/$USER/.aliaser/aliaser" ]]; then
        cp -r $SCRIPT_DIR/aliaser /home/$USER/.aliaser/bin
        find /home/$USER/.aliaser/bin -type f -exec chmod +x {} \;
fi

i=1
exists=0
while read -r line;
    do
        i=$((i + 1))
        if [[ "$line" == *"#ALIASER"* ]]; then
            exists=$((exists + 1))
            break
        fi
done < /home/$USER/.bashrc

exported=0
EXPORT_PATH='export PATH=$PATH":$HOME/.aliaser/bin"'
if [[ $exists -eq 1 ]]; 
    then
        while read -r line_2; do
            if [[ "$line_2" == *"$EXPORT_PATH"* ]]; then
                exported=$((exported + 1))
                break
            fi
        done < /home/$USER/.bashrc

        if [[ $exported -eq 0 ]]; then
            echo "" >> /home/$USER/.bashrc

            sed -i "${i}i${EXPORT_PATH}" /home/$USER/.bashrc
        fi

    else
        echo "#ALIASER" >> /home/$USER/.bashrc

        while read -r line_2; do
            if [[ "$line_2" == *"$EXPORT_PATH"* ]]; then
                exported=$((exported + 1))
                break
            fi
        done < /home/$USER/.bashrc

        if [[ $exported -eq 0 ]]; then
           echo "$EXPORT_PATH" >> /home/$USER/.bashrc
        fi
fi
